### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by dzdidi** [secucard/secucard-connect-javascript-sdk#2]
Hello, I would like to run tests of this code. Can you please provide information about it?

**Comment by valichek** [comment]
@dzdidi, You can find some test examples here https://github.com/secucard/secucard-connect-javascript-sdk/tree/master/spec

**Comment by valichek** [comment]
jasmine-es6 lib is used for testing the library code, it will be installed as a dependency after `npm install`

**Comment by smith64fx** [comment]
Nice thanks :D
