### ISSUE TITLE
Test Fails: "Source Device not found"

### ISSUE THREAD

**Issue by smith64fx** [secucard/secucard-connect-javascript-sdk#3]
Hi,
Today I tried to run the service-smart.spec test.

```
node_modules/jasmine-es6/bin/jasmine.js spec/service-smart.spe
c.js
```

When I ran it, I got this error:

```
Failures:
1) Smart Services gets list, creates/updates smart transaction with STOMP
  Message:
    Failed: Source Device not found
```

Unfortunately I have absolutely no idea what that means.

I used this endpoint for the test:
var oAuthUrl = 'https://connect-testing.secupay-ag.de/oauth/'
var stompHost = 'connect-testing.secupay-ag.de'

Do you have any idea about this problem?

**Comment by valichek** [comment]
@smith64fx Do you have valid credentials in `support/devCredentials.json` ?

**Comment by smith64fx** [comment]
Hi @valichek 
Thank you for your fast answer!

My code looks like this:
```
'use strict'
var SecucardConnect = require('secucard-connect').SecucardConnect;
var Services = require('secucard-connect').Services;
var ClientConfig = require('secucard-connect/dist/commonjs/de.secucard.connect/client-config.js').ClientConfig;

// set credentials
var credentials = {
    client_id: "xxxxx",
    client_secret: "yyyyyyy"
};

let config = ClientConfig.defaults()

// create Secucard client
var client = SecucardConnect.create({
    oAuthUrl: 'https://connect-testing.secupay-ag.de/oauth/',
    stompHost: 'connect-testing.secupay-ag.de'
});

client.setCredentials(credentials);

// get Smart/Transactions service
var smartTransactions = client.getService(Services.Smart.Transactions);

// subscribe for event
smartTransactions.on('display', function (data) {
    console.log('Display event', data);
})

// establish connection
client.open().then(function () {

    var devTransaction = require('./transaction')

    let data

    smartTransactions.create(devTransaction)
        .then((res) => {
            data = res;

            smartTransactions.start(data.id, "demo").then(function (res) {
                console.log('res')
                console.log(res);
            }).catch(function (err) {
                console.log('errr');
                console.log(err);
            });
        });
});
```

**Comment by valichek** [comment]
@smith64fx if you have valid credentials, but get device related errors you don't have device configured or authorized.

**Comment by smith64fx** [comment]
ah okay,
I'm sorry for the noob question but where can I do this or what the purpose of the device is?

Unfortunately there is not a lot of documentation ^_^"

Is there maybe a unofficial documentation or something like that?

pasiba brate!

**Comment by valichek** [comment]
@smith64fx to execute actions related to devices (like smart.transaction) you should have `deviceUUID` received from `secucard`. You can find an auth example for the device here https://github.com/secucard/secucard-connect-javascript-sdk/blob/master/spec/auth-device3.spec.js

**Comment by smith64fx** [comment]
@valichek Thank you again!

I just tested it and it seems to work :)

Is there any explanation why there is a deviceUUID necessary?
I could imagine it's because of different devices that are using the API.

Well we are building a crowdfunding platform so there is only one device (our server), is that right?

**Comment by valichek** [comment]
@smith64fx here is not a place for questions about how things work, you should make some request to `secucard` support.

**Comment by valichek** [comment]
@smith64fx could you provide the `client_id` you use to be more concrete

**Comment by smith64fx** [comment]
@valichek 
yes thanks.

the client id is:
09ae83af7c37121b2de929b211bad944

I will contact the support next time. thank you very much!
